name: Matrix Workflow

on:
  push:
    branches:
      - main

jobs:
  matrix:
    strategy:
      matrix:
        node-version: [12, 14, 16]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: node-app