name: Matrix Workflow

on:
  push:
    branches:
      - main

jobs:
  matrix:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: node-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
